<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chef_departement_controller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Chef_departement_model');
    } 

    /*
     * Listing of tb_chef_departement
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_chef_departement/index?');
        $config['total_rows'] = $this->Chef_departement_model->get_all_tb_chef_departement_count();
        $this->pagination->initialize($config);

        $data['tb_chef_departement'] = $this->Chef_departement_model->get_all_tb_chef_departement($params);
        
        $data['_view'] = 'chef_departement/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_chef_departement
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'date_creation' => $this->input->post('date_creation'),
				'privilege' => $this->input->post('privilege'),
				'signature_chef_dep' => $this->input->post('signature_chef_dep'),
            );
            
            $tb_chef_departement_id = $this->Chef_departement_model->add_tb_chef_departement($params);
            redirect('chef_departement_controller/index');
        }
        else
        {            
            $data['_view'] = 'chef_departement/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_chef_departement
     */
    function edit($chef_dep_id)
    {   
        // check if the tb_chef_departement exists before trying to edit it
        $data['tb_chef_departement'] = $this->Chef_departement_model->get_tb_chef_departement($chef_dep_id);
        
        if(isset($data['tb_chef_departement']['chef_dep_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'date_creation' => $this->input->post('date_creation'),
					'privilege' => $this->input->post('privilege'),
					'signature_chef_dep' => $this->input->post('signature_chef_dep'),
                );

                $this->Chef_departement_model->update_tb_chef_departement($chef_dep_id,$params);            
                redirect('chef_departement_controller/index');
            }
            else
            {
                $data['_view'] = 'chef_departement/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_chef_departement you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_chef_departement
     */
    function remove($chef_dep_id)
    {
        $tb_chef_departement = $this->Chef_departement_model->get_tb_chef_departement($chef_dep_id);

        // check if the tb_chef_departement exists before trying to delete it
        if(isset($tb_chef_departement['chef_dep_id']))
        {
            $this->Chef_departement_model->delete_tb_chef_departement($chef_dep_id);
            redirect('chef_departement_controller/index');
        }
        else
            show_error('The tb_chef_departement you are trying to delete does not exist.');
    }
    
}
