<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Daf_controller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Daf_model');
    } 

    /*
     * Listing of tb_daf
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_daf/index?');
        $config['total_rows'] = $this->Daf_model->get_all_tb_daf_count();
        $this->pagination->initialize($config);

        $data['tb_daf'] = $this->Daf_model->get_all_tb_daf($params);
        
        $data['_view'] = 'daf/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_daf
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'date_creation' => $this->input->post('date_creation'),
				'privilege' => $this->input->post('privilege'),
				'signature_daf' => $this->input->post('signature_daf'),
            );
            
            $tb_daf_id = $this->Daf_model->add_tb_daf($params);
            redirect('daf_controller/index');
        }
        else
        {            
            $data['_view'] = 'daf/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_daf
     */
    function edit($daf_id)
    {   
        // check if the tb_daf exists before trying to edit it
        $data['tb_daf'] = $this->Daf_model->get_tb_daf($daf_id);
        
        if(isset($data['tb_daf']['daf_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'date_creation' => $this->input->post('date_creation'),
					'privilege' => $this->input->post('privilege'),
					'signature_daf' => $this->input->post('signature_daf'),
                );

                $this->Daf_model->update_tb_daf($daf_id,$params);            
                redirect('daf_controller/index');
            }
            else
            {
                $data['_view'] = 'daf/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_daf you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_daf
     */
    function remove($daf_id)
    {
        $tb_daf = $this->Daf_model->get_tb_daf($daf_id);

        // check if the tb_daf exists before trying to delete it
        if(isset($tb_daf['daf_id']))
        {
            $this->Daf_model->delete_tb_daf($daf_id);
            redirect('daf_controller/index');
        }
        else
            show_error('The tb_daf you are trying to delete does not exist.');
    }
    
}
