<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dg_controller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Dg_model');
    } 

    /*
     * Listing of tb_dg
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_dg/index?');
        $config['total_rows'] = $this->Dg_model->get_all_tb_dg_count();
        $this->pagination->initialize($config);

        $data['tb_dg'] = $this->Dg_model->get_all_tb_dg($params);
        
        $data['_view'] = 'dg/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_dg
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'date_creation' => $this->input->post('date_creation'),
				'privilege' => $this->input->post('privilege'),
				'signature_dg' => $this->input->post('signature_dg'),
            );
            
            $tb_dg_id = $this->Dg_model->add_tb_dg($params);
            redirect('dg_controller/index');
        }
        else
        {            
            $data['_view'] = 'dg/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_dg
     */
    function edit($dg_id)
    {   
        // check if the tb_dg exists before trying to edit it
        $data['tb_dg'] = $this->Dg_model->get_tb_dg($dg_id);
        
        if(isset($data['tb_dg']['dg_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'date_creation' => $this->input->post('date_creation'),
					'privilege' => $this->input->post('privilege'),
					'signature_dg' => $this->input->post('signature_dg'),
                );

                $this->Dg_model->update_tb_dg($dg_id,$params);            
                redirect('dg_controller/index');
            }
            else
            {
                $data['_view'] = 'dg/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_dg you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_dg
     */
    function remove($dg_id)
    {
        $tb_dg = $this->Dg_model->get_tb_dg($dg_id);

        // check if the tb_dg exists before trying to delete it
        if(isset($tb_dg['dg_id']))
        {
            $this->Dg_model->delete_tb_dg($dg_id);
            redirect('dg_controller/index');
        }
        else
            show_error('The tb_dg you are trying to delete does not exist.');
    }
    
}
