<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fiche_besoin_controller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fiche_besoin_model');
    } 

    /*
     * Listing of tb_fiche_besoin
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tb_fiche_besoin/index?');
        $config['total_rows'] = $this->Fiche_besoin_model->get_all_tb_fiche_besoin_count();
        $this->pagination->initialize($config);

        $data['tb_fiche_besoin'] = $this->Fiche_besoin_model->get_all_tb_fiche_besoin($params);
        
        $data['_view'] = 'fiche_besoin/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_fiche_besoin
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nom_produit','Nom Produit','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'statut_fiche' => $this->input->post('statut_fiche'),
				'agent_id' => $this->input->post('agent_id'),
				'service_gen_id' => $this->input->post('service_gen_id'),
				'chef_dep_id' => $this->input->post('chef_dep_id'),
				'dg_id' => $this->input->post('dg_id'),
				'daf_id' => $this->input->post('daf_id'),
				'nom_produit' => $this->input->post('nom_produit'),
				'departement' => $this->input->post('departement'),
				'date_livraison' => $this->input->post('date_livraison'),
				'date_creation' => $this->input->post('date_creation'),
				'description' => $this->input->post('description'),
				'raison' => $this->input->post('raison'),
				'adresse_livraison' => $this->input->post('adresse_livraison'),
				'proformat_1' => $this->input->post('proformat_1'),
				'proformat_2' => $this->input->post('proformat_2'),
				'proformat_3' => $this->input->post('proformat_3'),
            );
            
            $tb_fiche_besoin_id = $this->Fiche_besoin_model->add_tb_fiche_besoin($params);
            redirect('fiche_besoin_controller/index');
        }
        else
        {
			$this->load->model('Agent_model');
			$data['all_tb_agent'] = $this->Agent_model->get_all_tb_agent();

			$this->load->model('Services_gen_model');
			$data['all_tb_services_gen'] = $this->Services_gen_model->get_all_tb_services_gen();

			$this->load->model('Chef_departement_model');
			$data['all_tb_chef_departement'] = $this->Chef_departement_model->get_all_tb_chef_departement();

			$this->load->model('Dg_model');
			$data['all_tb_dg'] = $this->Dg_model->get_all_tb_dg();

			$this->load->model('Daf_model');
			$data['all_tb_daf'] = $this->Daf_model->get_all_tb_daf();
            
            $data['_view'] = 'fiche_besoin/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_fiche_besoin
     */
    function edit($besoin_id)
    {   
        // check if the tb_fiche_besoin exists before trying to edit it
        $data['tb_fiche_besoin'] = $this->Fiche_besoin_model->get_tb_fiche_besoin($besoin_id);
        
        if(isset($data['tb_fiche_besoin']['besoin_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nom_produit','Nom Produit','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'statut_fiche' => $this->input->post('statut_fiche'),
					'agent_id' => $this->input->post('agent_id'),
					'service_gen_id' => $this->input->post('service_gen_id'),
					'chef_dep_id' => $this->input->post('chef_dep_id'),
					'dg_id' => $this->input->post('dg_id'),
					'daf_id' => $this->input->post('daf_id'),
					'nom_produit' => $this->input->post('nom_produit'),
					'departement' => $this->input->post('departement'),
					'date_livraison' => $this->input->post('date_livraison'),
					'date_creation' => $this->input->post('date_creation'),
					'description' => $this->input->post('description'),
					'raison' => $this->input->post('raison'),
					'adresse_livraison' => $this->input->post('adresse_livraison'),
					'proformat_1' => $this->input->post('proformat_1'),
					'proformat_2' => $this->input->post('proformat_2'),
					'proformat_3' => $this->input->post('proformat_3'),
                );

                $this->Fiche_besoin_model->update_tb_fiche_besoin($besoin_id,$params);            
                redirect('fiche_besoin_controller/index');
            }
            else
            {
				$this->load->model('Agent_model');
				$data['all_tb_agent'] = $this->Agent_model->get_all_tb_agent();

				$this->load->model('Services_gen_model');
				$data['all_tb_services_gen'] = $this->Services_gen_model->get_all_tb_services_gen();

				$this->load->model('Chef_departement_model');
				$data['all_tb_chef_departement'] = $this->Chef_departement_model->get_all_tb_chef_departement();

				$this->load->model('Dg_model');
				$data['all_tb_dg'] = $this->Dg_model->get_all_tb_dg();

				$this->load->model('Daf_model');
				$data['all_tb_daf'] = $this->Daf_model->get_all_tb_daf();

                $data['_view'] = 'fiche_besoin/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_fiche_besoin you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_fiche_besoin
     */
    function remove($besoin_id)
    {
        $tb_fiche_besoin = $this->Fiche_besoin_model->get_tb_fiche_besoin($besoin_id);

        // check if the tb_fiche_besoin exists before trying to delete it
        if(isset($tb_fiche_besoin['besoin_id']))
        {
            $this->Fiche_besoin_model->delete_tb_fiche_besoin($besoin_id);
            redirect('fiche_besoin_controller/index');
        }
        else
            show_error('The tb_fiche_besoin you are trying to delete does not exist.');
    }
    
}
