<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Services_gen_controller extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Services_gen_model');
    } 

    /*
     * Listing of tb_services_gen
     */
    function index()
    {
        $data['tb_services_gen'] = $this->Services_gen_model->get_all_tb_services_gen();
        
        $data['_view'] = 'services_gen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tb_services_gen
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'date_creation' => $this->input->post('date_creation'),
				'privilege' => $this->input->post('privilege'),
				'signature_serv' => $this->input->post('signature_serv'),
            );
            
            $tb_services_gen_id = $this->Services_gen_model->add_tb_services_gen($params);
            redirect('services_gen_controller/index');
        }
        else
        {            
            $data['_view'] = 'services_gen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tb_services_gen
     */
    function edit($service_gen_id)
    {   
        // check if the tb_services_gen exists before trying to edit it
        $data['tb_services_gen'] = $this->Services_gen_model->get_tb_services_gen($service_gen_id);
        
        if(isset($data['tb_services_gen']['service_gen_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'date_creation' => $this->input->post('date_creation'),
					'privilege' => $this->input->post('privilege'),
					'signature_serv' => $this->input->post('signature_serv'),
                );

                $this->Services_gen_model->update_tb_services_gen($service_gen_id,$params);            
                redirect('services_gen_controller/index');
            }
            else
            {
                $data['_view'] = 'services_gen/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tb_services_gen you are trying to edit does not exist.');
    } 

    /*
     * Deleting tb_services_gen
     */
    function remove($service_gen_id)
    {
        $tb_services_gen = $this->Services_gen_model->get_tb_services_gen($service_gen_id);

        // check if the tb_services_gen exists before trying to delete it
        if(isset($tb_services_gen['service_gen_id']))
        {
            $this->Services_gen_model->delete_tb_services_gen($service_gen_id);
            redirect('services_gen_controller/index');
        }
        else
            show_error('The tb_services_gen you are trying to delete does not exist.');
    }
    
}
