<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Chef_departement_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_chef_departement by chef_dep_id
     */
    function get_tb_chef_departement($chef_dep_id)
    {
        return $this->db->get_where('tb_chef_departement',array('chef_dep_id'=>$chef_dep_id))->row_array();
    }
    
    /*
     * Get all tb_chef_departement count
     */
    function get_all_tb_chef_departement_count()
    {
        $this->db->from('tb_chef_departement');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_chef_departement
     */
    function get_all_tb_chef_departement($params = array())
    {
        $this->db->order_by('chef_dep_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_chef_departement')->result_array();
    }
        
    /*
     * function to add new tb_chef_departement
     */
    function add_tb_chef_departement($params)
    {
        $this->db->insert('tb_chef_departement',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_chef_departement
     */
    function update_tb_chef_departement($chef_dep_id,$params)
    {
        $this->db->where('chef_dep_id',$chef_dep_id);
        return $this->db->update('tb_chef_departement',$params);
    }
    
    /*
     * function to delete tb_chef_departement
     */
    function delete_tb_chef_departement($chef_dep_id)
    {
        return $this->db->delete('tb_chef_departement',array('chef_dep_id'=>$chef_dep_id));
    }
}
