<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Daf_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_daf by daf_id
     */
    function get_tb_daf($daf_id)
    {
        return $this->db->get_where('tb_daf',array('daf_id'=>$daf_id))->row_array();
    }
    
    /*
     * Get all tb_daf count
     */
    function get_all_tb_daf_count()
    {
        $this->db->from('tb_daf');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_daf
     */
    function get_all_tb_daf($params = array())
    {
        $this->db->order_by('daf_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_daf')->result_array();
    }
        
    /*
     * function to add new tb_daf
     */
    function add_tb_daf($params)
    {
        $this->db->insert('tb_daf',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_daf
     */
    function update_tb_daf($daf_id,$params)
    {
        $this->db->where('daf_id',$daf_id);
        return $this->db->update('tb_daf',$params);
    }
    
    /*
     * function to delete tb_daf
     */
    function delete_tb_daf($daf_id)
    {
        return $this->db->delete('tb_daf',array('daf_id'=>$daf_id));
    }
}
