<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dg_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_dg by dg_id
     */
    function get_tb_dg($dg_id)
    {
        return $this->db->get_where('tb_dg',array('dg_id'=>$dg_id))->row_array();
    }
    
    /*
     * Get all tb_dg count
     */
    function get_all_tb_dg_count()
    {
        $this->db->from('tb_dg');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_dg
     */
    function get_all_tb_dg($params = array())
    {
        $this->db->order_by('dg_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_dg')->result_array();
    }
        
    /*
     * function to add new tb_dg
     */
    function add_tb_dg($params)
    {
        $this->db->insert('tb_dg',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_dg
     */
    function update_tb_dg($dg_id,$params)
    {
        $this->db->where('dg_id',$dg_id);
        return $this->db->update('tb_dg',$params);
    }
    
    /*
     * function to delete tb_dg
     */
    function delete_tb_dg($dg_id)
    {
        return $this->db->delete('tb_dg',array('dg_id'=>$dg_id));
    }
}
