<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fiche_besoin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_fiche_besoin by besoin_id
     */
    function get_tb_fiche_besoin($besoin_id)
    {
        return $this->db->get_where('tb_fiche_besoin',array('besoin_id'=>$besoin_id))->row_array();
    }
    
    /*
     * Get all tb_fiche_besoin count
     */
    function get_all_tb_fiche_besoin_count()
    {
        $this->db->from('tb_fiche_besoin');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_fiche_besoin
     */
    function get_all_tb_fiche_besoin($params = array())
    {
        $this->db->order_by('besoin_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_fiche_besoin')->result_array();
    }
        
    /*
     * function to add new tb_fiche_besoin
     */
    function add_tb_fiche_besoin($params)
    {
        $this->db->insert('tb_fiche_besoin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_fiche_besoin
     */
    function update_tb_fiche_besoin($besoin_id,$params)
    {
        $this->db->where('besoin_id',$besoin_id);
        return $this->db->update('tb_fiche_besoin',$params);
    }
    
    /*
     * function to delete tb_fiche_besoin
     */
    function delete_tb_fiche_besoin($besoin_id)
    {
        return $this->db->delete('tb_fiche_besoin',array('besoin_id'=>$besoin_id));
    }
}
