<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fournisseur_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_fournisseur by fournisseur_id
     */
    function get_tb_fournisseur($fournisseur_id)
    {
        return $this->db->get_where('tb_fournisseur',array('fournisseur_id'=>$fournisseur_id))->row_array();
    }
    
    /*
     * Get all tb_fournisseur count
     */
    function get_all_tb_fournisseur_count()
    {
        $this->db->from('tb_fournisseur');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tb_fournisseur
     */
    function get_all_tb_fournisseur($params = array())
    {
        $this->db->order_by('fournisseur_id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tb_fournisseur')->result_array();
    }
        
    /*
     * function to add new tb_fournisseur
     */
    function add_tb_fournisseur($params)
    {
        $this->db->insert('tb_fournisseur',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_fournisseur
     */
    function update_tb_fournisseur($fournisseur_id,$params)
    {
        $this->db->where('fournisseur_id',$fournisseur_id);
        return $this->db->update('tb_fournisseur',$params);
    }
    
    /*
     * function to delete tb_fournisseur
     */
    function delete_tb_fournisseur($fournisseur_id)
    {
        return $this->db->delete('tb_fournisseur',array('fournisseur_id'=>$fournisseur_id));
    }
}
