<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Services_gen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tb_services_gen by service_gen_id
     */
    function get_tb_services_gen($service_gen_id)
    {
        return $this->db->get_where('tb_services_gen',array('service_gen_id'=>$service_gen_id))->row_array();
    }
        
    /*
     * Get all tb_services_gen
     */
    function get_all_tb_services_gen()
    {
        $this->db->order_by('service_gen_id', 'desc');
        return $this->db->get('tb_services_gen')->result_array();
    }
        
    /*
     * function to add new tb_services_gen
     */
    function add_tb_services_gen($params)
    {
        $this->db->insert('tb_services_gen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tb_services_gen
     */
    function update_tb_services_gen($service_gen_id,$params)
    {
        $this->db->where('service_gen_id',$service_gen_id);
        return $this->db->update('tb_services_gen',$params);
    }
    
    /*
     * function to delete tb_services_gen
     */
    function delete_tb_services_gen($service_gen_id)
    {
        return $this->db->delete('tb_services_gen',array('service_gen_id'=>$service_gen_id));
    }
}
